Feature: Update comments by Posting API
Wes-Isaac/Capstone_project_2 pull request #27
Opened 2021-11-17 19:38 UTC by luftedar

# Feature: Post Comments to the API
In this update:
- Added 'post' for the comments.

2021-11-17 20:27 UTC, Wes-Isaac requested changes
# Status: Changes Required ♻️ 

Hello @luftedar, I am Isaac, your reviewer for this PR

Well done so far with your project!

Your project is almost perfect, congratulations! There are some really small details to correct before moving on, good luck!

I will mention to you a small summary of things that need to be changed in order to keep moving:

 Please check the comments below in this PR.

2021-11-17 20:27 UTC, Wes-Isaac commented on src/index.js
> +  console.log(id);
Please remove console logs from your code they might contain private data and makes the site slow.

2021-11-17 20:27 UTC, Wes-Isaac commented on src/index.js
> +  };
This try and catch block doesn't take action when the API responds with a 404. Please fix that.

2021-11-17 20:27 UTC, Wes-Isaac commented on src/index.js
>        <img src="${movies[parseInt(e.target.parentNode.id) - 1].image.medium}" alt="${movies[parseInt(e.target.parentNode.id) - 1].name}">
The index you're passing to the movies array is not a number, please fix that.

2021-11-17 20:27 UTC, Wes-Isaac commented on src/index.js
> +          <button id="${id}" type="button">Submit Comment</button>
All id attributes should be unique in the code. Please make all id's unique.

2021-11-18 08:16 UTC, luftedar commented
### Hi @Wes-Isaac 
Fixed the bugs and implement required changes :+1:

2021-11-18 08:20 UTC, Wes-Isaac commented
# Status: Approved 💯 
You've done a great job of implementing project requirements.

It is time to merge 🥇

2021-11-18 08:33 UTC, Wes-Isaac approved these changes

2021-11-18 08:43 UTC, merged